# Generated by Django 4.2.2 on 2023-06-18 08:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('usertype', models.CharField(choices=[('E', 'EMPLOYER'), ('R', 'RECRUITER')], max_length=1)),
                ('short_desc', models.CharField(max_length=25)),
                ('self_desc', models.TextField()),
                ('portfolio', models.CharField(blank=True, max_length=225, null=True)),
                ('cv', models.FileField(upload_to='cv', validators=[django.core.validators.FileExtensionValidator(['PDF', 'docx'])])),
                ('user_condition', models.CharField(choices=[('E', 'EMPLOED'), ('UE', 'UNEMPLOED')], max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Profile.skill')),
            ],
        ),
    ]
