# Generated by Django 4.2.2 on 2023-06-18 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv', validators=[django.core.validators.FileExtensionValidator(['PDF', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='self_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='short_desc',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_condition',
            field=models.CharField(choices=[('E', 'EMPLOED'), ('UE', 'UNEMPLOED')], default='UE', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='usertype',
            field=models.CharField(choices=[('E', 'EMPLOYER'), ('R', 'RECRUITER')], default='E', max_length=1),
        ),
    ]
