# Generated by Django 4.2.2 on 2023-06-18 08:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverletter', models.TextField()),
                ('relatedworks', models.FileField(blank=True, null=True, upload_to='related_works', validators=[django.core.validators.FileExtensionValidator(['PDF', 'docx'])])),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiraChategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SiraType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('P', 'PERMANENT'), ('C', 'CONTRAT'), ('F', 'FREELANCING'), ('PE', 'PAID_INTERNSHIP'), ('UE', 'UNPAID_INTERNSHIP')], default='P', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Sira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componsation_type', models.CharField(choices=[('M', 'MONTHLY'), ('H', 'HOURLY'), ('F', 'FIXED_PRICE')], default='M', max_length=1)),
                ('componsation', models.IntegerField()),
                ('componsation_range', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('requirement', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('delete', models.BooleanField(default=False)),
                ('closed_reason', models.CharField(choices=[('G', 'GETIN GETSIRA'), ('US', 'UNSATISFAID'), ('OP', 'GETINOTHER PLACE'), ('O', 'GETINOTHERPLACE')], max_length=2)),
                ('date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('chategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Main.sirachategory')),
            ],
        ),
    ]
