# Generated by Django 4.2.2 on 2023-06-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sira',
            name='closed_reason',
            field=models.CharField(blank=True, choices=[('G', 'GETIN GETSIRA'), ('US', 'UNSATISFAID'), ('OP', 'GETINOTHER PLACE'), ('O', 'GETINOTHERPLACE')], max_length=2, null=True),
        ),
    ]
